title: Kestrun Docs
description: Kestrun documentation
url: https://kestrun.github.io
baseurl: ""

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings

permalink: pretty

# 🔧 Defaults define the sidebar relationships
defaults:
  - scope: { path: "" }
    values:
      layout: default
      nav_exclude: false
      render_with_liquid: false

just_the_docs:
  search:
    enabled: true
