title: Kestrun Docs
description: Kestrun documentation
url: https://kestrun.github.io
baseurl: ""   # user/org site → keep empty

# Sidebar theme with built-in search
remote_theme: just-the-docs/just-the-docs

# GitHub Pages supports these plugins
plugins:
  - jekyll-remote-theme
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings

# Make Jekyll treat your generated MD nicely
defaults:
  - scope:
      path: "docs"       # no leading slash
    values:
      layout: default
      parent: "PowerShell Cmdlets"    # all pages nest under this in the sidebar
      nav_exclude: false
      render_with_liquid: false       # prevents Liquid from eating {{ placeholders }}

# Pretty URLs like /Get-KrThing/
permalink: pretty

# Turn on search box
just_the_docs:
  search:
    enabled: true
